### ISSUE TITLE
Creating a live ILDA show

### ISSUE THREAD

**Issue by bgnt44** [colouredmirrorball/Ilda#1]
Hi,
First great work, i totally support your idea of using processing as ILDA file generator
Then I would like to know what you think about using your library for real time ILDA communication using thoses cheap Ilda interface ( example Helios DAC) , thoses device deliver dll and sdk file
and manly the frame structure is very close to ilda file (x,y,r,g,b,i);

Do you have something in mind that could cause issue ?

 Thanks for your work

**Comment by colouredmirrorball** [comment]
Hey,

I have done some work on this. LSX has a feature where you can send a frame to it over OSC. This works fine, just some parsing.

Your application could work but the main issue is that you need to load a C++ library in java. There are ways to do this but I never got it working right, so for now I'm focussing on network oriented DACs and protocols (Etherdream, IDN, OSC to LSX and so on).

For real time output, you might also want to reduce the framerate of the sketch to match the DAC speed.

**Comment by bgnt44** [comment]
You can load any dll using JNI , I do it already for DMX and it works quite well , at least on windows...( soon testing with .so for Linux) 

Using a third party software like LSX could be a good idea too

**Comment by colouredmirrorball** [comment]
I think the main issue might be timing. When do you need to send a frame? When using OSC to LSX this wasn't an issue. I just sent a frame at 60 fps because it just overwrites a slot in LSX' internal frame buffer. LSX will then take care of the frame rate that is sent to the dac.

The problem here is that such behaviour is DAC dependent. So you'd need different logic for every device.

**Comment by bgnt44** [comment]
When i think more about it, there is a bunch of function that could be handled by LSX like blind spots and projection angle.. but actually processing can run on a raspberry pi including those usb DAC using libusb , then u can just pilot ur raspberry with any network compatible interface like tablet

Then for the fps , it can be set to 30, the main work gonna be how to efficiently render shapes in the most logical order ... cause now i have issue with blanking (testing device is a chinese rgb laser with no blanking other than color dimming)

**Comment by colouredmirrorball** [comment]
I have added an example sketch that demonstrates how to send an IldaFrame to LSX using the OSC protocol. This example requires the newest LSX version. https://github.com/colouredmirrorball/Ilda/tree/master/examples/RectanglesToLSX
