### ISSUE TITLE
Ellipse is not centered

### ISSUE THREAD

**Issue by jcrbcn** [colouredmirrorball/Ilda#2]
Hi there,

Why do I have to write this to draw a circle that covers all the canvas:
`r.ellipse(width*0.75,height*0.75,width/2,height/2);`

Instead of this, which is how I'd do it with the normal Processing shape:

`ellipse(width/2,height/2,width,height);`

I get this if I do it in the usual way:
![image](https://user-images.githubusercontent.com/24853329/40578489-20f993d8-6115-11e8-8b00-7aeed1696306.png)

Thanks a lot 👍

**Comment by colouredmirrorball** [comment]
Thanks for the report, I could reproduce the bug. Looks like I mistakenly thought ellipse() uses the radius and not the diameter as its inputs!

**Comment by colouredmirrorball** [comment]
Newest release should fix the issue.

**Comment by jcrbcn** [comment]
Yes! It works now!

Thank you very much!

**Comment by jcrbcn** [comment]
In that case it works, but with other examples such as this:

`ellipse(0,width/2, 100, 100);`

I get this:

![image](https://user-images.githubusercontent.com/24853329/40579383-6a119654-6126-11e8-90f6-1f83d913b47b.png)

(where the upper circle is the one from the renderer)

**Comment by colouredmirrorball** [comment]
Let me do a proper testing this time...

**Comment by colouredmirrorball** [comment]
New version should work... perhaps.

**Comment by jcrbcn** [comment]
Yes it does! Thanks 😎
