### ISSUE TITLE
Double lined paths

### ISSUE THREAD

**Issue by jcrbcn** [colouredmirrorball/Ilda#3]
Hi again,

It looks like to draw some shapes, the laser is doing more than one line for path. Is that right?

Is there a way to reduce the number of those lines in order to draw more complex frames?

![img_9731](https://user-images.githubusercontent.com/24853329/40578715-1ae6f932-6119-11e8-99fe-4bbe0faa2574.JPG)

Thanks 😃

**Comment by colouredmirrorball** [comment]
Are you talking about the vertical stripes in your picture, or do you mean the circle is traced multiple times?

Are you loading the ilda file directly into your laser or are you using a program for output?

**Comment by jcrbcn** [comment]
I'm talking about the multiple traces of the circle. The stripes are part of a cross for calibration.
And I'm using the IldaframeToLSX for real-time.

**Comment by colouredmirrorball** [comment]
The library should only send as many points as you generated by it. Anything that LSX does is beyond my control.

You can reduce the amount of points in the circle by using `r.setEllipseDetail(float detail)`. The default value does indeed generate quite some points. Try `r.setEllipseDetail(0.1)`, or to taste.
You're not using `setEllipseCorrection()`, are you? This method adds extra overshoot points to the ellipse to ensure the gap is closed.

I have recently made some changes to the LSX OSC output examples that solves some issues, namely blanking. It now uses the format that sends blanking information, so the built-in LSX optimisation procedures are more effective.

**Comment by jcrbcn** [comment]
Ok, seems like it's an LSX problematic. Thanks for the tips!
